"""MTG keyword rules definitions for flashcard generation."""
# ruff: noqa: E501

KEYWORD_DEFINITIONS: dict[str, str] = {
    # Keyword Abilities
    "Deathtouch": "Any amount of damage this deals to a creature is enough to destroy it.",
    "Defender": "This creature can't attack.",
    "Double strike": "This creature deals both first-strike and regular combat damage.",
    "Enchant": "This Aura can be attached to the specified permanent or player.",
    "Equip": "Attach this Equipment to target creature you control. Equip only as a sorcery.",
    "First strike": "This creature deals combat damage before creatures without first strike.",
    "Flash": "You may cast this spell any time you could cast an instant.",
    "Flying": "This creature can't be blocked except by creatures with flying or reach.",
    "Haste": "This creature can attack and tap as soon as it comes under your control.",
    "Hexproof": "This permanent can't be the target of spells or abilities your opponents control.",
    "Indestructible": "Effects that say 'destroy' don't destroy this. Lethal damage doesn't destroy it.",
    "Intimidate": "This creature can't be blocked except by artifact creatures and/or creatures that share a color with it.",
    "Landwalk": "This creature can't be blocked as long as defending player controls a land of the specified type.",
    "Lifelink": "Damage dealt by this creature also causes you to gain that much life.",
    "Menace": "This creature can't be blocked except by two or more creatures.",
    "Protection": "This permanent can't be damaged, enchanted, equipped, blocked, or targeted by anything with the specified quality.",
    "Reach": "This creature can block creatures with flying.",
    "Shroud": "This permanent can't be the target of spells or abilities.",
    "Trample": "This creature can deal excess combat damage to the player or planeswalker it's attacking.",
    "Vigilance": "Attacking doesn't cause this creature to tap.",
    "Ward": "Whenever this permanent becomes the target of a spell or ability an opponent controls, counter it unless that player pays the ward cost.",
    # Evergreen keyword abilities
    "Convoke": "Your creatures can help cast this spell. Each creature you tap while casting reduces the cost by {1} or one mana of that creature's color.",
    "Cycling": "Discard this card and pay the cycling cost to draw a card.",
    "Flashback": "You may cast this card from your graveyard for its flashback cost, then exile it.",
    "Kicker": "You may pay an additional cost as you cast this spell for an enhanced effect.",
    "Prowess": "Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.",
    "Scry": "Look at the top N cards of your library. Put any number on the bottom and the rest back on top in any order.",
    "Surveil": "Look at the top N cards of your library. Put any number into your graveyard and the rest back on top in any order.",
    "Toxic": "Players dealt combat damage by this creature also get N poison counters.",
    "Affinity": "This spell costs {1} less for each permanent of the specified type you control.",
    "Annihilator": "Whenever this creature attacks, defending player sacrifices N permanents.",
    "Cascade": "When you cast this spell, exile cards from the top of your library until you exile a nonland card that costs less. You may cast it without paying its mana cost.",
    "Changeling": "This card is every creature type.",
    "Crew": "Tap any number of creatures you control with total power N or more: This Vehicle becomes an artifact creature until end of turn.",
    "Delve": "Each card you exile from your graveyard while casting this spell pays for {1}.",
    "Devoid": "This card has no color.",
    "Emerge": "You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature's mana value.",
    "Embalm": "Exile this card from your graveyard and pay the embalm cost: Create a token copy that's white with no mana cost.",
    "Enlist": "As this creature attacks, you may tap a nonattacking creature you control without summoning sickness. When you do, add its power to this creature's power until end of turn.",
    "Escape": "You may cast this card from your graveyard for its escape cost (exile N other cards from your graveyard).",
    "Eternalize": "Exile this card from your graveyard and pay the eternalize cost: Create a 4/4 token copy that's black with no mana cost.",
    "Evoke": "You may cast this spell for its evoke cost. If you do, sacrifice it when it enters the battlefield.",
    "Exploit": "When this creature enters the battlefield, you may sacrifice a creature for an additional effect.",
    "Exalted": "Whenever a creature you control attacks alone, that creature gets +1/+1 until end of turn.",
    "Fabricate": "When this creature enters the battlefield, put N +1/+1 counters on it or create N 1/1 Servo tokens.",
    "Foretell": "During your turn, you may pay {2} and exile this card face down. Cast it on a later turn for its foretell cost.",
    "Improvise": "Your artifacts can help cast this spell. Each artifact you tap while casting reduces the cost by {1}.",
    "Investigate": "Create a Clue artifact token with '{2}, Sacrifice this artifact: Draw a card.'",
    "Living weapon": "When this Equipment enters the battlefield, create a 0/0 black Phyrexian Germ creature token, then attach this to it.",
    "Madness": "If you discard this card, discard it into exile. You may cast it for its madness cost.",
    "Meld": "If you control both halves of a meld pair, exile them and combine them into the melded card.",
    "Morph": "You may cast this card face down as a 2/2 creature for {3}. Turn it face up any time for its morph cost.",
    "Mutate": "Pay the mutate cost to cast on top of or under a non-Human creature you own. They mutate into one creature.",
    "Ninjutsu": "Return an unblocked attacker you control to hand and put this card from your hand onto the battlefield attacking.",
    "Overload": "Pay the overload cost to change 'target' to 'each' in the spell's text.",
    "Persist": "When this creature dies, if it had no -1/-1 counters, return it with a -1/-1 counter.",
    "Proliferate": "Choose any number of permanents and/or players with counters, then give each another counter of a kind already there.",
    "Prototype": "You may cast this spell with different mana cost, power, toughness, and color.",
    "Raid": "This ability triggers or improves if you attacked with a creature this turn.",
    "Rebound": "If you cast this spell from your hand, exile it as it resolves. At the beginning of your next upkeep, cast it again without paying its mana cost.",
    "Reconfigure": "Attach/unattach this to target creature you control. Reconfigure only as a sorcery. While attached, this isn't a creature.",
    "Retrace": "You may cast this card from your graveyard by discarding a land card in addition to paying its other costs.",
    "Spectacle": "You may cast this spell for its spectacle cost if an opponent lost life this turn.",
    "Storm": "When you cast this spell, copy it for each spell cast before it this turn.",
    "Suspend": "Exile this card with N time counters. At the beginning of your upkeep, remove a time counter. When the last is removed, cast it without paying its mana cost.",
    "Threshold": "This ability is active as long as you have seven or more cards in your graveyard.",
    "Transform": "Turn this double-faced card over to its other face.",
    "Treasure": "Create a Treasure artifact token with 'Tap, Sacrifice: Add one mana of any color.'",
    "Undying": "When this creature dies, if it had no +1/+1 counters, return it with a +1/+1 counter.",
    "Unearth": "Return this card from your graveyard to the battlefield. It gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield.",
    "Wither": "This deals damage to creatures in the form of -1/-1 counters.",
    # Keyword Actions
    "Attach": "Move an Aura, Equipment, or Fortification onto a permanent.",
    "Counter": "A countered spell or ability is removed from the stack and has no effect.",
    "Destroy": "Move a permanent from the battlefield to its owner's graveyard.",
    "Discard": "Put a card from your hand into your graveyard.",
    "Exile": "Move a card to the exile zone, face up unless otherwise specified.",
    "Fight": "Two creatures each deal damage equal to their power to the other.",
    "Mill": "Put the top N cards of your library into your graveyard.",
    "Sacrifice": "Move a permanent you control to its owner's graveyard. Can't be regenerated.",
    "Tap/Untap": "Rotate a permanent 90 degrees (tap) or back to upright (untap).",
    "Create": "Put a token onto the battlefield with the specified characteristics.",
    "Connive": "Draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on this creature.",
    "Discover": "Exile cards from the top of your library until you exile a nonland card with mana value N or less. Cast it without paying its mana cost or put it into your hand.",
    "Adapt": "If this creature has no +1/+1 counters on it, put N +1/+1 counters on it.",
    "Amass": "Put N +1/+1 counters on an Army you control. If you don't control one, create a 0/0 black Zombie Army creature token first.",
    "Bolster": "Choose a creature you control with the least toughness. Put N +1/+1 counters on it.",
    "Ascend": "If you control ten or more permanents, you get the city's blessing for the rest of the game.",
    "Venture": "Move to the next room of a dungeon. If you're not in a dungeon, choose one to enter.",
    "Incubate": "Create an Incubator token with N +1/+1 counters. Pay {2} to transform it into a 0/0 Phyrexian creature.",
    "The Ring tempts you": "Choose a creature as your Ring-bearer. It gains abilities as the Ring's influence grows.",
    "Collect evidence": "Exile cards with total mana value N or greater from your graveyard.",
}
